build:
  stage: build
  image: nixos/nix:latest
  tags:
    - cn
  script:
    - sed -i "s/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g" /etc/apk/repositories
    - apk add curl
    - |
      echo "substituters = https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store https://cache.nixos.org/" >> /etc/nix/nix.conf
    - nix-channel --add https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable nixpkgs
    - nix-channel --add https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixos-20.09 nixos
    - nix-channel --update
    - https_proxy=http://192.168.122.88:8123 curl -s -L https://github.com/clash-lang/clash-compiler/archive/1.2.tar.gz | tar xz
    - nix-shell clash-compiler-1.2/shell.nix
    - ls -lash
